package Exception_handling;


public class e3 {

	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		
		try {
			int result = 0/1;
		}
		catch(ArithmeticException e)
		{
			System.out.println("Arithmatic exception");
			
		}
		catch(NullPointerException y )
		{
			
		}
	}

}
